# Generated by Django 3.2.7 on 2021-09-09 01:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0002_auto_20210908_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='NIT',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
